### ISSUE TITLE
Received malformed payload after socket.send_party_data_async

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama-godot#101]
`send_party_data_async` causes a fatal failure that ultimately closes the socket

```
{"level":"warn","ts":"2022-04-07T20:25:27.605-0600","caller":"server/session_ws.go:239","msg":"Received malformed payload","uid":"97345292-110a-4ebf-96b8-6605e8021957","sid":"23131abe-b6e3-11ec-9ba4-006100a0eb06","data":"eyJjaWQiOiI0IiwicGFydHlfZGF0YV9zZW5kIjp7InBhcnR5X2lkIjoiNGY3YjdlZDUtMTYwMC00NjYyLWJmODQtYTgxNzRlNDc3YWNkLm5ha2FtYSIsIm9wX2NvZGUiOjMsImRhdGEiOiJbMTE0LCAxMDEsIDk3LCAxMDAsIDEyMV0ifX0="}
```

eg)
sending anything for `data` fails:

`socket.send_party_data_async(party_id, 2,  "12345")`
or
`socket.send_party_data_async(party_id, 2,  "12345".to_utf8())`

this does not fail:
`socket.send_party_data_async(party_id, 2)`

**Comment by jasonwinterpixel** [comment]
Found the problem. I looked in realtime.proto to find other messages that were using `bytes`. I found one: MatchData. In Nakama godot, match data is wrapped in `Marshalls.utf8_to_base64()`


This is the fix:
```
func send_party_data_async(p_party_id : String, p_op_code : int, p_data:String = ""):
	return _send_async(NakamaRTMessage.PartyDataSend.new(p_party_id, p_op_code, Marshalls.utf8_to_base64(p_data)))
```
I will submit this as a PR. Not sure if sending empty string is different than sending null here.

**Comment by dsnopek** [comment]
Good find, thanks!

> Not sure if sending empty string is different than sending null here.

I think `null` will cause the data to be omitted entirely.

We could do it like:

```
func send_party_data_async(p_party_id : String, p_op_code : int, p_data:String = ""):
	return _send_async(NakamaRTMessage.PartyDataSend.new(p_party_id, p_op_code, Marshalls.utf8_to_base64(p_data) if p_data else null))
```

> I will submit this as a PR.

Looking forward to the PR!

**Comment by dsnopek** [comment]
@jasonwinterpixel Do you still plan to make a PR for this? If not I can make one (although, your help testing it would be much appreciated :-)) Thanks!

**Comment by jasonwinterpixel** [comment]
Sorry for delay. Fixed here:
https://github.com/heroiclabs/nakama-godot/pull/106
