### ISSUE TITLE
Godot-4: Error when emitting a "received_matchmaker_matched" signal

### ISSUE THREAD

**Issue by artem-krutov** [heroiclabs/nakama-godot#115]
Hey guys.

I know that `godot-4` branch is in development now, but still decided to file this issue to help you in searches for some bugs, if you don't mind.

So, in `NakamaSocket` we are emitting signals:
```
...
elif dict.has("matchmaker_matched"):
	var res = NakamaRTAPI.MatchmakerMatched.create(NakamaRTAPI, dict["matchmaker_matched"])
	emit_signal("received_matchmaker_matched", res)
...
```
If we look at the method `NakamaRTAPI.MatchmakerMatched.create`, we will see the following impl:
```
static func create(p_ns : GDScript, p_dict : Dictionary) -> MatchmakerMatched:
	return _safe_ret(NakamaSerializer.deserialize(p_ns, "MatchmakerMatched", p_dict), MatchmakerMatched) as MatchmakerMatched
```
So the `res` should definitely be an instance of `NakamaRTAPI.MatchmakerMatched`.

Then, let's go to my code. I have a signal connected:
```
# setup socket
socket.connect("received_matchmaker_matched", self._on_matchmaker_matched)
```
And the handler function:
```
func _on_matchmaker_matched(p_matched : NakamaRTAPI.MatchmakerMatched):
	print("Received MatchmakerMatched message: %s" % [p_matched])
	print("Matched opponents: %s" % [p_matched.users])
```
As a result, the signal is emitted, but with the error 37: METHOD NOT FOUND. 
The problem is in the method signature. I declare `p_matched` as `NakamaRTAPI.MatchmakerMatched`, and the signal couldn't be emitted. But if I declare `p_matched` as just an `Object`, then my method will be found and invoked.

Not sure what's the reason of that problem, and if it's on Nakama's side. But anyway, seems like an issues.

Thanks!

**Comment by dsnopek** [comment]
Closing because, unfortunately, there's nothing we can do from this end
