### ISSUE TITLE
Client doesn't work with godot 4.x

### ISSUE THREAD

**Issue by Mohsen7s** [heroiclabs/nakama-godot#119]
## Description
Error and unrecognized NakamaClient after autoloaded in Godot 4.
NakamaClient need a few lines of refactoring so it fit to 4.x breaking changes

List of changes to 4.x include following:
1. Yield removed. use await instead.
2. export, tool and a few keywords need a @ before it (@tool)
3. Syntax for set_ and get_ properties changed
4. A few changes to OS class( removed get_unix_time)

## Steps to Reproduce
1.Download Godot 4 beta or the last alpha
5. Autoload Nakama just like 3.x versions
6. Try to make a new NakamaClient instance

## Expected Result
It should work fine with godot 4.x versions

## Actual Result
Only errors

## Context
- [ ] Unity
- [ ] Unreal
- [ X] Godot

## Your Environment
Doesn't matter as it block at very first stage

**Comment by dsnopek** [comment]
Hi! Are you using the ['godot-4' branch](https://github.com/heroiclabs/nakama-godot/tree/godot-4) of the addon?

> Yield removed. use await instead.
> export, tool and a few keywords need a @ before it (@tool)
> Syntax for set_ and get_ properties changed
> A few changes to OS class( removed get_unix_time)

All of these changes were already made in the 'godot-4' branch!

**Comment by Mohsen7s** [comment]
Yes, Im using it and I saw some part of code which has not been refactored or you forgot it.
It might be because of conversion from old godot project. Ill try to test it against a new project and report what happens.
Can you please merge 4.0 branch to main and release a new version ? 
That will help to find bugs more easily by contributor reports. Not all beginner game designer know we have 4.0 branch so they are waiting for a release.

**Comment by dsnopek** [comment]
> Yes, Im using it and I saw some part of code which has not been refactored or you forgot it.

There shouldn't be! If you can point to a specific instance (file/line), I'd be happy to fix it. :-)

> Can you please merge 4.0 branch to main and release a new version ?

There will be a release at some point! The Godot 4 support is still alpha (like Godot 4 itself) and we need to figure out how to publish an asset in Godot's asset library that has two different versions for Godot 3 and 4. The Godot 3 version will probably still be the one in the main branch until Godot 4.0's stable release.

**Comment by dsnopek** [comment]
I'm going to close this for now. We can always reopen it if you're able to provide file names and line numbers for code that wasn't ported to Godot 4!

That said, the test suite is passing in Godot 4, and I have couple little test projects that are working as well.
