### ISSUE TITLE
This is more of a suggestion

### ISSUE THREAD

**Issue by stonekase** [heroiclabs/nakama-godot#12]
I Think you guys can work with the author of this https://gitlab.com/dsnopek/godot-nakama-gdscript

His module seems to be more mature , maybe it can be colapsed to one project.

**Comment by novabyte** [comment]
@stonekase I reached out before Christmas to the author of that library but it was my fault we could not collaborate. We'd hired to work with an engineer that contributes to the Godot engine on network code. We're very happy with Fabio's work.

> His module seems to be more mature , maybe it can be collapsed to one project.

Can you describe what could be added to reach parity with that library?

**Comment by jonbonazza** [comment]
FWIW I actually used that library before switching to the official one and unfortunately, it was littered eith bugs, especially around the realtime api. I am honestly much happier with the official api.

**Comment by stonekase** [comment]
> @stonekase I reached out before Christmas to the author of that library but it was my fault we could not collaborate. We'd hired to work with an engineer that contributes to the Godot engine on network code. We're very happy with Fabio's work.
> 
> > His module seems to be more mature , maybe it can be collapsed to one project.
> 
> Can you describe what could be added to reach parity with that library?

Well still testing it out, but it seems not to use signals to split functions.

**Comment by stonekase** [comment]
> FWIW I actually used that library before switching to the official one and unfortunately, it was littered eith bugs, especially around the realtime api. I am honestly much happier with the official api

True, battling with one :(
