### ISSUE TITLE
[Error] Couldn't fully load the singleton script "Nakama"

### ISSUE THREAD

**Issue by dev-clavis** [heroiclabs/nakama-godot#120]
Installing this asset by following the installation guide causes this error

## Steps to reproduce
1. Create New Project
2. Install Asset
3. Add Nakama.gd to autoload with name Nakama
4. Create Empty Scene with one Node
5. Add New Script to that Node with following content
```
extends Node

func _ready():
	var scheme = "http"
	var host = "127.0.0.1"
	var port = 7350
	var server_key = "defaultkey"
	var client := Nakama.create_client(server_key, host, port, scheme)
```
6. Run Scene

## Error Details

```
func _ready() -> void:
	Nakama.pause_mode = Node.PAUSE_MODE_PROCESS
```

res://addons/com.heroiclabs.nakama/Nakama.gd:26 - Parse Error: Couldn't fully load the singleton script "Nakama" (possible cyclic reference or parse error).

## V
* Godot: 3.3.3 Stable
* OS: Win10

**Comment by dev-clavis** [comment]
It is interesting when looking at a working example (https://github.com/heroiclabs/fishgame-godot), that these lines don't exist in the Nakama.gd

**Comment by dsnopek** [comment]
Thanks for the report!

I think if we changed the line to:

```
pause_mode = Node.PAUSE_MODE_PROCESS
```

Removing the `Nakama.` in front of it, it would fix the problem.
