### ISSUE TITLE
Godot - Godot 4 status

### ISSUE THREAD

**Issue by grusad** [heroiclabs/nakama-godot#123]
Hello!

Godot 4 beta just release and ive been waiting for quite a while now to migrate my current project from 3.5 to 4.0. Now might be the time. I just want to know the current state of the godot-4 branch?  Am i able to migrate now or should i wait a bit longer? 

I hope its ok for me to open an issue as a question, of not. Sorry for that :)

**Comment by luiscesjr** [comment]
I'm also migrating my project from 3.x to 4.0, and the main issue I'm having right now is about a class_name bug in Godot 4, does not seem to be Nakama specific. It was reported [here #65620](https://github.com/godotengine/godot/issues/65620) and [here #60997](https://github.com/godotengine/godot/issues/60997).

Given Beta was just released yesterday, there's a long way to come from both sides for sure.

**Comment by grusad** [comment]
I did encounter this problem[62989](https://github.com/godotengine/godot/issues/62982) when nakama tried to emit signals.

But this does not seem to be related to nakama rather to Gdscript 2.0.

But I am curious how @luiscesjr did get passed that problem. Mine throws an error at line 217 inside NakamaSocket.gd.

**Comment by luiscesjr** [comment]
> But I am curious how @luiscesjr did get passed that problem. Mine throws an error at line 217 inside NakamaSocket.gd.

Line 217 of Nakama Socket for me is

			var res = NakamaRTAPI.MatchData.create(NakamaRTAPI, dict["match_data"])

Then on 218 there is a signal emittion, but I really don't get any errors there. Aside for a lot of await functions I had to rework, my main issues were done after getting the 4-branch files. Also I had a lot of singletons errors, but that's all engine related not nakama's.

**Comment by dsnopek** [comment]
The 'godot-4' branch should be working, with the caveat that there's a bunch of bugs in Godot 4 beta1 currently, particularly around type hints. To get the Godot 4 version working we had to remove type hints from several places, which you may have to do in your code as well.
