### ISSUE TITLE
Update C# support classes to work with Godot 4

### ISSUE THREAD

**Issue by dsnopek** [heroiclabs/nakama-godot#128]
There are some C# support classes in `addons/com.heroiclabs.nakama/mono-utils/` which haven't yet been updated to work with Godot 4. Let's fix that!

The directory should also probably be renamed, since Godot 4 will be using .NET 6, rather than mono. (Maybe 'dotnet-utils'?)

**Comment by novabyte** [comment]
@dsnopek I don't remember what these utils were required for. Do you think they can be eliminated in favour of just using the .NET client as a dependency with a Godot project?

**Comment by dsnopek** [comment]
@novabyte The support classes work together with the Nakama .NET client, in order to integrate a little better with Godot, in particular allowing the HTML5 export to work. The Unity client has similar support classes.

The description in the "Mono / C#" section of the README is pretty good, if you want some more details!
