### ISSUE TITLE
Synchronizer and Spawner nodes

### ISSUE THREAD

**Issue by WolfgangSenff** [heroiclabs/nakama-godot#136]
Howdy folks. I've finally started looking into using Nakama and was just wanting to make sure: does it support the new nodes in Godot 4? I imagine so, since I believe they're built on top of the rpc high level code, but it would be cool to get an example of it.

**Comment by dsnopek** [comment]
Yes, if you use the `NakamaMultiplayerBridge`, the new scene synchronization nodes will work

**Comment by dsnopek** [comment]
Closing, since there isn't really anything actionable here
