### ISSUE TITLE
About "WebSocket" Supporting "Godot4.0_Beta3"

### ISSUE THREAD

**Issue by 316902108** [heroiclabs/nakama-godot#137]
When will the "WebSocket" support of "Godot4.0_Beta3" be updated? I tried to fix it, but failed!

**Comment by peterkingsbury** [comment]
I had moderate success with the following:
- Add [gd-websocket-nodes](https://github.com/Faless/gd-websocket-nodes) to your project, under its `addons` folder;
- Update `WebSocketClient` enums to match those found under WebSocketPeer`;
- Map some functions (e.g. `close()`) to their counterparts in the new WebSocketClient/WebSocketPeer interface.

Can't say for sure whether this will outright fix all issues, but it enabled me to proceed beyond the few Nakama-related errors I was getting.

**Comment by dominiks** [comment]
There's an open PR (https://github.com/heroiclabs/nakama-godot/pull/135)  you can apply yourself until it's merged into the dev4 branch.

**Comment by dsnopek** [comment]
Fixed in PR #135
