### ISSUE TITLE
Will "Nakama_Godot" increase the "P2P" network capability?

### ISSUE THREAD

**Issue by 316902108** [heroiclabs/nakama-godot#138]
Will "Nakama_Godot" increase the "P2P" network capability?
I think this is a good network capability！
I hope "Nakama" can have this ability!
Use the "Nakama" server as the judge to build a "P2P" network bridge for the client。

**Comment by dsnopek** [comment]
Godot support WebRTC for peer-to-peer networking, and it's possible to use Nakama as a signalling server for WebRTC (allowing the peers to find a way to connect directly to each other).

There's an existing addon (the "WebRTC and Nakama" addon) in the asset library:

https://godotengine.org/asset-library/asset/884

You can find a tutorial here:

https://www.snopekgames.com/tutorial/2021/how-use-webrtc-godot-nakama-signalling-server

I hope this helps!
