### ISSUE TITLE
NakamaException : Missing or invalid required prop {name:token, required:True, type:4} (NakamaRTAPI.gd) Bug

### ISSUE THREAD

**Issue by stonekase** [heroiclabs/nakama-godot#14]
I get this returned by the admatcher Please see below:

var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")

func _on_received_matchmaker_matched(p_matchmaker_matched):
	print("Matcher Mathced  : ",p_matchmaker_matched)

The Above callback returns below 👍 

NakamaException(StatusCode={-1}, Message='{ERROR [MatchmakerMatched]: Missing or invalid required prop {name:token, required:True, type:4} = Null:
	{match_id:c415e717-05d8-4a80-a65d-c4b89e9f0fac.nakama-node-1, self:{presence:{session_id:32925588-dd57-4c65-90a3-48d6366f33a6, user_id:1831b11b-2da0-4e46-a2be-f8e8a5d3f530, username:ashtonkase}}, ticket:aa3f28df-4047-44ee-a2c7-b748acdb7fd6, users:[{presence:{session_id:32925588-dd57-4c65-90a3-48d6366f33a6, user_id:1831b11b-2da0-4e46-a2be-f8e8a5d3f530, username:ashtonkase}}, {presence:{session_id:fafdaff4-efaf-4579-aa2e-f491e8fcc74f, user_id:889c3b43-eeb1-4c73-983f-bc76ca04ac9d, username:G:10115341080}}]}}', GrpcStatusCode={-1})

Message sent by Nakama Server :

<img width="912" alt="Screenshot 2020-02-09 at 08 17 51" src="https://user-images.githubusercontent.com/5037778/74098138-cb45cd80-4b14-11ea-8aca-b586d349253a.png">
{"level":"debug","ts":"2020-02-09T08:12:52.527+0100","msg":"Sending *rtapi.Envelope_Match message","uid":"889c3b43-eeb1-4c73-983f-bc76ca04ac9d","sid":"f5e8dbd9-8cce-40f3-87d0-b2aa20d36760","envelope":"cid:\"3\" match:<match_id:\"f73a0761-b07a-4330-87c7-ad0c8ace2fdd.nakama-node-1\" authoritative:true label:<value:\"Quickplay\" > size:1 presences:<user_id:\"1831b11b-2da0-4e46-a2be-f8e8a5d3f530\" session_id:\"b8543803-e856-4ca5-b37c-2a3b1ce0e5bb\" username:\"ashtonkase\" > self:<user_id:\"889c3b43-eeb1-4c73-983f-bc76ca04ac9d\" session_id:\"f5e8dbd9-8cce-40f3-87d0-b2aa20d36760\" username:\"G:10115341080\" > > "}

<img width="934" alt="Screenshot 2020-02-09 at 07 28 31" src="https://user-images.githubusercontent.com/5037778/74097602-17414400-4b0e-11ea-96da-a14bea574e3e.png">

NakamaRTAPI.gd: (I think the issue is from the below class  ,but still trying to figure it out)
class MatchmakerMatched extends NakamaAsyncResult:

**Comment by stonekase** [comment]
> I get this returned by the admatcher Please see below:
> 
> var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")
> 
> func _on_received_matchmaker_matched(p_matchmaker_matched):
> print("Matcher Mathced : ",p_matchmaker_matched)
> 
> The Above callback returns below 👍
> 
> NakamaException(StatusCode={-1}, Message='{ERROR [MatchmakerMatched]: Missing or invalid required prop {name:token, required:True, type:4} = Null:
> {match_id:c415e717-05d8-4a80-a65d-c4b89e9f0fac.nakama-node-1, self:{presence:{session_id:32925588-dd57-4c65-90a3-48d6366f33a6, user_id:1831b11b-2da0-4e46-a2be-f8e8a5d3f530, username:ashtonkase}}, ticket:aa3f28df-4047-44ee-a2c7-b748acdb7fd6, users:[{presence:{session_id:32925588-dd57-4c65-90a3-48d6366f33a6, user_id:1831b11b-2da0-4e46-a2be-f8e8a5d3f530, username:ashtonkase}}, {presence:{session_id:fafdaff4-efaf-4579-aa2e-f491e8fcc74f, user_id:889c3b43-eeb1-4c73-983f-bc76ca04ac9d, username:G:10115341080}}]}}', GrpcStatusCode={-1})
> 
> Message sent by Nakama Server :
> 
> <img alt="Screenshot 2020-02-09 at 08 17 51" width="912" src="https://user-images.githubusercontent.com/5037778/74098138-cb45cd80-4b14-11ea-8aca-b586d349253a.png">
> 
> {"level":"debug","ts":"2020-02-09T08:12:52.527+0100","msg":"Sending *rtapi.Envelope_Match message","uid":"889c3b43-eeb1-4c73-983f-bc76ca04ac9d","sid":"f5e8dbd9-8cce-40f3-87d0-b2aa20d36760","envelope":"cid:\"3\" match: size:1 presences: self: > "}
> <img alt="Screenshot 2020-02-09 at 07 28 31" width="934" src="https://user-images.githubusercontent.com/5037778/74097602-17414400-4b0e-11ea-96da-a14bea574e3e.png">
> 
> NakamaRTAPI.gd: (I think the issue is from the below class ,but still trying to figure it out)
> class MatchmakerMatched extends NakamaAsyncResult:

I founnd the problem in the Library code NakamaRTAPI.gd (class MatchPresenceEvent extends NakamaAsyncResult). the SCHEMA has a token which is invalid so hashing it out doesnt throw an exception now but then the message received comes with angled-brackets .
See below:
<img width="1261" alt="Screenshot 2020-02-09 at 09 19 59" src="https://user-images.githubusercontent.com/5037778/74098916-e10bc080-4b1d-11ea-9d66-4545d29b2ef8.png">

**Comment by Faless** [comment]
Hi, thank you for reporting this issue.
The response seems very strange, an `Envelope_Match` shouldn't generate a `matchmaker_matched` event, only an `Envelope_MatchMakerMatched` should.
What version of Nakama server are you using?
Does the following code work for you? (run two godot instances and it should match)

```gdscript
extends Control

const SERVER_ADDRESS = "127.0.0.0.1" # Change this to your IP

var client : NakamaClient
var socket : NakamaSocket

func _matched(p_matched):
	print("MatchMakerMatched: ", p_matched)

func _ready():
	client = Nakama.create_client("defaultkey", SERVER_ADDRESS)
	# Authenticate first account.
	var session : NakamaSession = yield(client.authenticate_custom_async("myuniqueid"), "completed")
	print("Session ", session)
	socket = Nakama.create_socket_from(client)
	socket.connect("received_matchmaker_matched", self, "_matched")
	var connected = yield(socket.connect_async(session), "completed")
	print(connected)
	var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")
	print("Ticket ", ticket)
```

Can you provide a minimum reproduction project in case?

**Comment by stonekase** [comment]
> Hi, thank you for reporting this issue.
> The response seems very strange, an `Envelope_Match` shouldn't generate a `matchmaker_matched` event, only an `Envelope_MatchMakerMatched` should.
> What version of Nakama server are you using?
> Does the following code work for you? (run two godot instances and it should match)
> 
> ```gdscript
> extends Control
> 
> const SERVER_ADDRESS = "127.0.0.0.1" # Change this to your IP
> 
> var client : NakamaClient
> var socket : NakamaSocket
> 
> func _matched(p_matched):
> 	print("MatchMakerMatched: ", p_matched)
> 
> func _ready():
> 	client = Nakama.create_client("defaultkey", SERVER_ADDRESS)
> 	# Authenticate first account.
> 	var session : NakamaSession = yield(client.authenticate_custom_async("myuniqueid"), "completed")
> 	print("Session ", session)
> 	socket = Nakama.create_socket_from(client)
> 	socket.connect("received_matchmaker_matched", self, "_matched")
> 	var connected = yield(socket.connect_async(session), "completed")
> 	print(connected)
> 	var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")
> 	print("Ticket ", ticket)
> ```
> 
> Can you provide a minimum reproduction project in case?

actually i have found the problem in NakamaRTAPI.gd

### <summary>
### A batch of join and leave presences for a match.
### </summary>
class MatchPresenceEvent extends NakamaAsyncResult:
	const _SCHEMA = {
		"match_id": {"name": "match_id", "type": TYPE_STRING, "required": true},
		"joins": {"name": "joins", "type": TYPE_ARRAY, "required": false, "content" : "UserPresence"},
		"leaves": {"name": "leaves", "type": TYPE_ARRAY, "required": false, "content" : "UserPresence"},
	}

	### <summary>
	### Presences of users who joined the match.
	### </summary>
	var joins : Array

	### <summary>
	### Presences of users who left the match.
	### </summary>
	var leaves : Array

	### <summary>
	### The unique match identifier.
	### </summary>
	var match_id : String

	func _init(p_ex = null).(p_ex):
		pass

	func _to_string():
		if is_exception(): return get_exception()._to_string()
		return "MatchPresenceEvent<match_id=%s, joins=%s, leaves=%s>" % [match_id, joins, leaves]

	static func create(p_ns : GDScript, p_dict : Dictionary) -> MatchPresenceEvent:
		return _safe_ret(NakamaSerializer.deserialize(p_ns, "MatchPresenceEvent", p_dict), MatchPresenceEvent) as MatchPresenceEvent

	static func get_result_key() -> String:
		return "match_presence_event"

**Comment by Faless** [comment]
I'm not sure I understand, where is exactly the problem you found?

**Comment by stonekase** [comment]
> I'm not sure I understand, where is exactly the problem you found?

on the SCHEMA in class MatchmakerMatched (NakamaRTAPI.gd), The schema contains a variable "token".Token is not sent by the nakama server (Nakama 2.8).So if you hash out token from the SCHEMA and to_string function. it doesnt throw the exception.

**Comment by Faless** [comment]
But as per the docs `MatchmakerMatched` **must have** the token:
https://heroiclabs.com/docs/gameplay-matchmaker/#join-a-match

The problem from you log appears to be that the SDK is trying to parse a `Match` as a `MatchMakerMatched` but I don't understand why.

**Comment by stonekase** [comment]
> But as per the docs `MatchmakerMatched` **must have** the token:
> https://heroiclabs.com/docs/gameplay-matchmaker/#join-a-match
> 
> The problem from you log appears to be that the SDK is trying to parse a `Match` as a `MatchMakerMatched` but I don't understand why.
The link above you shared is for join match not Match_maker Matched
Well i can send you a zipped copy of my script causing the problem.I am immediately join a match after the matchmaker_matched callback is fired.

**Comment by Faless** [comment]
Well, it does state:
> Each matchmaker result event carries a token

But looking at the server code I've noticed is defined as oneof `match_id` or `token`.
I'll go on and make a fix, but if you can still send me the script it would be great so I can make a small reproduction case and add a test for it.

**Comment by stonekase** [comment]
> Well, it does state:
> 
> > Each matchmaker result event carries a token
> 
> But looking at the server code I've noticed is defined as oneof `match_id` or `token`.
> I'll go on and make a fix, but if you can still send me the script it would be great so I can make a small reproduction case and add a test for it.

Alright, Script below:
[Quickplay.gd.zip](https://github.com/heroiclabs/nakama-godot/files/4176616/Quickplay.gd.zip)

**Comment by Faless** [comment]
Thank you very much, I'll push a fix ASAP.

**Comment by stonekase** [comment]
> Thank you very much, I'll push a fix ASAP.

Just to add to this, Please have a look at NakamaSocket.gd.The result has a 'cid' but also has 'matchmaker_matched' . now if cid (which is 3) is captured .

**Comment by Faless** [comment]
If it has a `cid` it is a response to an async call, specifically, given that it's a `Match`, probably a response to `create_match_async`, `join_match_async` or `join_matched_async`.
