### ISSUE TITLE
NakamaHTTPAdapter use HTTPRequest and threads with a drop of FPS

### ISSUE THREAD

**Issue by fcazalet** [heroiclabs/nakama-godot#140]
Hello everybody. This Addon is very good. I just found something I want to share here.
I got FPS drop each time I do a call to Nakama Server.

I have found something weird with the use of HTTPRequest and use_threads to true.

Godot documentation say that using threads could improve performances.
But I have done a little test with a Timer of 2sec that do a GET request with HTTPRequest and use_threads to true.
With this option it appear that after the request the engine lose 1 or 2 frames. Maybe to synch threads stop.

So I think you can remove from Nakama Godot Addon the part `set_use_threads(true)` in NakamaHTTPAdapter. The use of yield do the asynch job.

I tested on my game and I have no more FPS drops.

**Comment by dsnopek** [comment]
Hm, thanks for sharing your experience! What platform are you seeing the frame drop on? What version of Godot are you using?

That code has been in for a long time, I think since the repo was originally created! I'll investigate and see if enabling threading still makes sense.

**Comment by fcazalet** [comment]
I'm using Windows 10 64bits with Godot 3.5.1

I created an example repository there: https://github.com/fcazalet/godot-test-httprequest

**Comment by dsnopek** [comment]
Sorry for the massive delay in getting back to you!

As best as I can tell, it's still best practice to enable threads when possible. Looking at the code in Godot, when threads are enabled, it spawns a new thread and processes the entire request there. Without threads, it's attempting to connect immediately (so blocking for the initial connection) and then polling every frame on the main thread until the request completes.

So, I'd actually expect to see the reverse behavior than you're seeing! My only thought is that perhaps the act of creating a new thread is really slow on your system?

Anyway, I don't think we should change the default, but we could certainly add a property to `NakamaHTTPAdaptor` to allow you to disable threading in your game.

**Comment by fcazalet** [comment]
Thank you for your changes ! 👍
