### ISSUE TITLE
New errors on startup using latest Godot 4 Beta

### ISSUE THREAD

**Issue by luiscesjr** [heroiclabs/nakama-godot#141]
So I've just downloaded the new Godot  v4.0.beta5.official [89a33d28f], and my project which was working (Still is on the beta 1), won't start.
And I checked, Nakama is in the autoload list.

This is the first one to pop up and break: (Nakama.gd file)

![image](https://user-images.githubusercontent.com/7636427/202468673-8e675963-0a13-4828-ab54-0d64c864fded.png)

But it continues on other files from Nakama: (NakamaSocketAdapter.gd file)

![image](https://user-images.githubusercontent.com/7636427/202468589-ec4a3862-55bb-4e41-ad69-d2bc02034db0.png)

**Comment by 316902108** [comment]
https://github.com/godotengine/godot-cpp/pull/896/commits/0e81f89dd3ea7418573075a716dcdd94b73e8621
Uses StringName in GDExtension perf critical instance creation & method/properties setter/getter #896

"Godot4.0_Beta5" Changes have taken place here, but I don't know how to deal with them

**Comment by dsnopek** [comment]
I did find some things that need to be updated for the latest Godot beta's, and made a PR https://github.com/heroiclabs/nakama-godot/pull/142

However, looking at the errors in your screenshots, I think you're missing the changes from PR https://github.com/heroiclabs/nakama-godot/pull/135

I'd recommend updating to the latest from the first PR that I linked above. The Godot beta's are still making breaking changes, so if you update to a new beta, you should probably check back here to see if there have been any new PRs or changes committed to the 'godot-4' branch
