### ISSUE TITLE
Parse error: Could not find type "p_type" in current scope.

### ISSUE THREAD

**Issue by grusad** [heroiclabs/nakama-godot#158]
Parse error: Could not find type "p_type" in current scope.

Godot 4 is complaining in the  _sate_ret function. Any fix for this? :)

**Comment by Mohamed-Kr** [comment]
This should fix it : #159

**Comment by Coxcopi** [comment]
Same issue here, the pull request mentioned by @Mohamed-Kr (#159) does indeed seem to fix this.

**Comment by dsnopek** [comment]
Thanks! This is fixed in PR #157 which has just been merged :-)
