### ISSUE TITLE
socket.send_match_state_async Sending Malformed data to Nakama server

### ISSUE THREAD

**Issue by stonekase** [heroiclabs/nakama-godot#16]
Nakama server : 2.10.0+e27ac0d2
Godot : 3.2 stable
OS : Mac OSX Catalina

How to reproduce:

create two clients , add clients to matcher-handler for a two player match(authoritative).
Send a  Socket data message to server ::

var dict = {"ready":"ready"}
var jstr = JSON.print(dict)
print("Json :",jstr)
var ready = yield(socket.send_match_state_async(p_match_presence_event.match_id,110,jstr),"completed")	
print("Ready !!! ", ready)

**Please Note an empty string doesnt throw an error.

Nakama Error ::

{"level":"warn","ts":"2020-02-14T18:42:10.700+0100","msg":"Received malformed payload","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"dd51ceab-a3ae-4a53-b583-565019fb3752","data":"eyJjaWQiOiI0IiwibWF0Y2hfZGF0YV9zZW5kIjp7Im1hdGNoX2lkIjoiNGRlOTQ5MDQtOWQyNy00NjQ3LWFmYTYtNGNiNGFkY2Y1YzJhLm5ha2FtYS1ub2RlLTEiLCJvcF9jb2RlIjoiMTEwIiwiZGF0YSI6IntcInJlYWR5XCI6XCJyZWFkeVwifSJ9fQ=="}
{"level":"info","ts":"2020-02-14T18:42:10.700+0100","msg":"Cleaning up closed client connection","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"dd51ceab-a3ae-4a53-b583-565019fb3752"}
{"level":"info","ts":"2020-02-14T18:42:10.700+0100","msg":"Cleaned up closed connection matchmaker","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"dd51ceab-a3ae-4a53-b583-565019fb3752"}
{"level":"info","ts":"2020-02-14T18:42:10.700+0100","msg":"Cleaned up closed connection tracker","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"dd51ceab-a3ae-4a53-b583-565019fb3752"}
{"level":"info","ts":"2020-02-14T18:42:10.700+0100","msg":"Cleaned up closed connection session registry","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"dd51ceab-a3ae-4a53-b583-565019fb3752"}

**Comment by novabyte** [comment]
I took a look at the decoded output of the message:

```
{"cid":"4","match_data_send":{"match_id":"4de94904-9d27-4647-afa6-4cb4adcf5c2a.nakama-node-1","op_code":"110","data":"{\"ready\":\"ready\"}"}}
```

The problem is that `op_code` is expected as a numeric value but is encoded as a string in the message content.

@stonekase do you want to make the quick change and open a pull request?

**Comment by Faless** [comment]
The problem appears to be here, `TYPE_STRING` should be `TYPE_INT`:
https://github.com/heroiclabs/nakama-godot/blob/861dc846d5a2e9b91944531797e5e826f4c48dda/addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd#L231

**Comment by stonekase** [comment]
> I took a look at the decoded output of the message:
> 
> ```
> {"cid":"4","match_data_send":{"match_id":"4de94904-9d27-4647-afa6-4cb4adcf5c2a.nakama-node-1","op_code":"110","data":"{\"ready\":\"ready\"}"}}
> ```
> 
> The problem is that `op_code` is expected as a numeric value but is encoded as a string in the message content.
> 
> @stonekase do you want to make the quick change and open a pull request?

sorry for the delayed response , I was in transit.Let me do that.

**Comment by stonekase** [comment]
> The problem appears to be here, `TYPE_STRING` should be `TYPE_INT` for the `op_code` property:
> 
> https://github.com/heroiclabs/nakama-godot/blob/861dc846d5a2e9b91944531797e5e826f4c48dda/addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd#L231

let me check it out.

**Comment by stonekase** [comment]
> The problem appears to be here, `TYPE_STRING` should be `TYPE_INT` for the `op_code` property:
> 
> https://github.com/heroiclabs/nakama-godot/blob/861dc846d5a2e9b91944531797e5e826f4c48dda/addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd#L231

Well , i made the below changes but Still having issues.

NakamaRTMessage.gd
Line 231 : "op_code": {"name": "op_code", "type": TYPE_INT, "required": true},
Line 254 : return "MatchDataSend<match_id=%s, op_code=%d, presences=%s, data=%s>" % [match_id,int(op_code), presences, data]

NakamaSocket.gd
func send_match_state_async(p_match_id, p_op_code : int, p_data : String, p_presences = null):
	var req = _send_async(NakamaRTMessage.MatchDataSend.new(
		p_match_id,
		p_op_code,
		p_data,
		p_presences
	))
	req.call_deferred("resume", {})
	call_deferred("_survive", req)
	return req

func send_match_state_raw_async(p_match_id, p_op_code : int, p_data : PoolByteArray, p_presences = null):
	return _send_async(NakamaRTMessage.MatchDataSend.new(
		p_match_id,
		p_op_code,
		Marshalls.raw_to_base64(p_data),
		p_presences
	))

Error::
{"level":"info","ts":"2020-02-16T07:20:02.736+0100","msg":"Wallet Data '10'","mid":"bac74eac-75e5-468a-ae0a-a04716dada32","runtime":"lua"}
{"level":"warn","ts":"2020-02-16T07:20:02.739+0100","msg":"Received malformed payload","uid":"1831b11b-2da0-4e46-a2be-f8e8a5d3f530","sid":"0a9b145b-2533-4ad4-8e89-c8205890a409","data":"eyJjaWQiOiI0IiwibWF0Y2hfZGF0YV9zZW5kIjp7Im1hdGNoX2lkIjoiYmFjNzRlYWMtNzVlNS00NjhhLWFlMGEtYTA0NzE2ZGFkYTMyLm5ha2FtYS1ub2RlLTEiLCJvcF9jb2RlIjoxMTAsImRhdGEiOiJ7XCJyZWFkeVwiOlwicmVhZHlcIn0ifX0="}

**Comment by stonekase** [comment]
looking at the decrypted response by @novabyte  , Can this be the reason for the int conversion back to string before sending the socket message?  @Faless 

 https://godotengine.org/qa/42997/how-to-load-integers-from-a-saved-game

**Comment by Faless** [comment]
@stonekase yeah, the fix was a bit more complex than expected, can you give #17 a try?

**Comment by stonekase** [comment]
> @stonekase yeah, the fix was a bit more complex than expected, can you give #17 a try?

This solves the problem, Many Thanks.
