### ISSUE TITLE
Network ridiculously slow

### ISSUE THREAD

**Issue by theromis** [heroiclabs/nakama-godot#160]
Built physics based game on top of godot 4 and finally realized client have about .5 second delay.
Finally found this client sends every packet to `nakama_socket` this is probably the reason, because pure godot host and client works as a blast. Is it possible to not send any packets during multiplayer?

https://github.com/heroiclabs/nakama-godot/blob/godot-4/addons/com.heroiclabs.nakama/utils/NakamaMultiplayerBridge.gd#L353-L363

https://github.com/godotengine/godot/issues/74207

**Comment by theromis** [comment]
@novabyte I know you the men, can you help with it? :)

**Comment by mofirouz** [comment]
Please do not tag individuals. The network rate depends on many factors, including how/where you’ve setup your Nakama instance, server resources, the match tick rate, rate of client message sending, and others. Feel free to post on the forum as this is not a SDK bug.

**Comment by theromis** [comment]
Seems like I need [Session-based multiplayer](https://heroiclabs.com/docs/nakama/concepts/multiplayer/#session-based-multiplayer) but I can't find this logic in [Nakama godot client](https://github.com/heroiclabs/nakama-godot)
Can somebody help me?
