### ISSUE TITLE
Nakama does not work for Godot 4.0

### ISSUE THREAD

**Issue by kawht** [heroiclabs/nakama-godot#167]
I have been trying for the past two days now to get Nakama to work nice with Godot 4.0. So far, every route I have gone down has made Godot throw many errors.

What I have tried:
- Download the official Asset from AssetLib in Godot (does not function, gives several errors)
- Download the latest release via Github (more errors)
- Download the raw code from the github (because last release is older than the some code changes)

All of the above has issues. I would assume it's mostly syntax problems. I have also tried Godot 4.2, but no change.
I am so tired of it. Please let me know what I can do and/or what information you need from me to help fix this problem.

Screenshot:
![nakama-broke](https://user-images.githubusercontent.com/13322922/232110358-a5a0d290-d086-41e7-bd24-26b5d2ebf274.PNG)

**Comment by dsnopek** [comment]
Sorry for all the frustration!

The latest release and the code on the asset library are broken in Godot 4.0 stable. The code in the 'godot-4' branch on GitHub should be working though.

> Download the raw code from the github (because last release is older than the some code changes)

Did you download the code from the 'godot-4' branch?

In any case, we really need to make a new release that works! I'll try to take care of that as soon as possible.

**Comment by dsnopek** [comment]
FYI, I just made a new v3.3.1 release:

https://github.com/heroiclabs/nakama-godot/releases/tag/v3.3.1

The update for the asset library has been submitted, but it usually takes a few days for those to get approved.

Please let me know if the latest version works any better for you!

**Comment by dsnopek** [comment]
The Godot 4 version has now moved to the 'master' branch. So, hopefully, that'll clear up any confusion about this in the future!

I'm going to close this one for now, but please let me know if you're still having issues, and we can certainly re-open it :-)
