### ISSUE TITLE
Socket is not working with Godot 4

### ISSUE THREAD

**Issue by septN** [heroiclabs/nakama-godot#168]
Authentication is working, but when I try to do socket connection, it does connect but immediately the client is closing the connection afterwards

This is what the server see
![image](https://user-images.githubusercontent.com/13846022/232287079-7e2b9e0a-0f1c-493a-a0cf-5e4bed7a92ec.png)

But on the client side, it doesn't recognize that it's been closing the socket, the _on_socket_closed() never get called
![image](https://user-images.githubusercontent.com/13846022/232287136-38f1a252-07d1-4bbb-ae50-def7e9bdd65f.png)

**Comment by dsnopek** [comment]
Thanks for the report!

Unfortunately, I'm not able to reproduce the issue. When testing with Nakama 3.15.0, Godot 4.0.2 and the latest code in the 'godot-4' branch here, I'm able to make a socket connection and use it to create matches and it doesn't close on its own.

Can you provide some more details? What version of Nakama and this addon are you using?

**Comment by septN** [comment]
> Thanks for the report!
> 
> Unfortunately, I'm not able to reproduce the issue. When testing with Nakama 3.15.0, Godot 4.0.2 and the latest code in the 'godot-4' branch here, I'm able to make a socket connection and use it to create matches and it doesn't close on its own.
> 
> Can you provide some more details? What version of Nakama and this addon are you using?
False flag from me. 

I just tested it again with the latest godot-4 branch. Then I noticed that I lazily put 
`var socket = `
inside _ready function. Of course this would cause the socket to be deleted once it get out of scope. Moving it up right where it belongs, works as intended.
