### ISSUE TITLE
Nakama plugin not visible in Godot 4.0.3

### ISSUE THREAD

**Issue by xenicle** [heroiclabs/nakama-godot#176]
I've installed the Nakama client plugin in my project (from AssetLib menu) and it not appear in Project Setting -> Plugins, I've tried to restart Godot without result...

![image](https://github.com/heroiclabs/nakama-godot/assets/26338409/b4f362b8-92be-411c-814a-5ca7259d6c9f)

**Comment by dsnopek** [comment]
This library doesn't need to be enabled in Project Setting -> Plugins, you only need to add "Nakama.gd" as an autoload.

Per the instructions ["Getting Started" instructions](https://github.com/heroiclabs/nakama-godot#getting-started) from the README:

> Add the `Nakama.gd` singleton (in `addons/com.heroiclabs.nakama/`) as an [autoload in Godot](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html).

I hope that helps!

**Comment by xenicle** [comment]
Oh yes thanks it help why I've not check the readme ?! :/

**Comment by novabyte** [comment]
@xenicle Looks like @dsnopek helped resolve the issue you had with the setup. I'll close the issue, thanks 🙏
