### ISSUE TITLE
`HTTPRequest.useThreads = true` flag causes issues on HTML5 export

### ISSUE THREAD

**Issue by andreyrk** [heroiclabs/nakama-godot#19]
The `req.use_threads = true` line on `client/NakamaHTTPAdapter.gd` causes the `HTTPClient blocking mode is not supported for the HTML5 platform.` and `At: platform/javascript/http_client_javascript.cpp:201:set_blocking_mode() - Condition "p_enable" is true.` devconsole warnings and fails the request with exception `NakamaException(StatusCode={8}, Message='{HTTPRequest failed!}', GrpcStatusCode={-1})``.

I believe as threads aren't supported on HTML5 exports, would be best to check for `OS.get_name() != "HTML5"`. Alternatively, exposing the setting to the developer could avoid both manually editing the API & future changes that might make multithreading feasible on the web.

**Comment by Faless** [comment]
Yeah, threads should be disabled in HTML5, It's weird that it then fails the request though. It sill should complete (though with the warning you mentioned). I'll investigate

**Comment by Faless** [comment]
I confirm that the request failing is an issue in Godot, I'll propose a fix upstream, in the meantime I'll disable them in HTML5 exports for the sdk (they are not needed, http requests are always async in the browsers).
