### ISSUE TITLE
Connection closes when passing restored session to NakamaSocket.connect_async

### ISSUE THREAD

**Issue by andreyrk** [heroiclabs/nakama-godot#21]
Attempting to connect a NakamaSocket from a NakamaSession restored from a token fails and emits signal `closed`. I might be missing something here such as having to wait for a signal from the session before connecting or something of the sort, so if that's the case would like to suggest adding a note on the Docs (also please don't forget to tell me here :]).

**Comment by novabyte** [comment]
@andreyrk What session timeout have you set in the server? The default value is 60 seconds as a reminder to set the token expiry time to a value that's a multiple of the game session play times. For example you might use 86,400 for a 7 day token lifetime.

You can set the value in the server with the cmdflag `--session.token_expiry_sec <val>` and also set it in the server YML configuration file if you prefer.

**Comment by andreyrk** [comment]
Thanks for the quick reply, I have set it to 2160000 (25 days) on a .yml file where I also set the server_key and etc.

**Comment by novabyte** [comment]
@andreyrk Ok great. can you share the YML file contents inline here? or check the devconsole UI to make sure the settings have taken effect when the server is active?

**Comment by andreyrk** [comment]
Of course, here are the contents as I do not have access to the server's display (I'm able to check any logs though if any are outputted with such)

```
name: nakama
data_dir: /var/lib/nakama-data

socket:
	server_key: "redacted"

session:
	token_expiry_ms: 21600000

runtime:
	http_key: "redacted"
```

**Comment by novabyte** [comment]
@andreyrk Your key should be called `token_expiry_sec` rather than `token_expiry_ms`. For example in the YML file it should be:

```yml
session:
    token_expiry_sec: 21600000
```

Please try that and let me know.

**Comment by andreyrk** [comment]
@novabyte Ah thank you, that does the trick 😄, but BTW `NakamaSession.is_expired()` seems to be reversed (true when not expired, false when expired):
```
func is_expired() -> bool:
	return expire_time - OS.get_unix_time() > 0
```
So you folks might want to take a peek at that!
Cheers.

**Comment by Faless** [comment]
> So you folks might want to take a peek at that!
> Cheers.

Woah, that was really a silly bug, thanks for reporting it! :+1:
