### ISSUE TITLE
GDscript demo code is absent in the document 

### ISSUE THREAD

**Issue by alexzheng** [heroiclabs/nakama-godot#23]
The GDscript demo code is absent in each feature demonstration code list.
Such as https://heroiclabs.com/docs/storage-collections/

**Comment by novabyte** [comment]
Thanks @alexzheng. That's a good reminder. We've not had the chance to add these to the various code snippets on the feature pages. Pull requests are welcome if you have time. :)

**Comment by novabyte** [comment]
@alexzheng This is now addressed in a pull request on the docs. https://github.com/heroiclabs/nakama-docs/pull/127
It will be available online shortly. 👍
