### ISSUE TITLE
HTML5 export can't connect 

### ISSUE THREAD

**Issue by Lerrrtaste** [heroiclabs/nakama-godot#30]
Hello,
after playing around with the Godot integration (having used nakama and godot in previous projects) I noticed that html5 exports can’t connect to the server. I get Status Code = 8 and Message HTTPRequest Failed, so a pretty generic error I think.

The documentation explicitly says html5 works ([here](https://heroiclabs.com/docs/godot-client-guide/#html5-exports)) so why doesnt it?

The same exact build for Linux works flawlessly as usual only html exports (tested with godots local debug html5 server, with nginx on my website and itch.io html hosting) can’t ever connect.

Do I need special settings for html exports? Or what else could cause this?

**Comment by novabyte** [comment]
@Lerrrtaste Do you have more information you can share:

- Is Nakama running behind a load balancer?
- What port number are you using to connect with the server?
- Do you have any browser extensions that could interfere with the traffic?
- Have you used a custom SSL certificate configured with the server?

**Comment by Lerrrtaste** [comment]
1. No I'm trying to connect directly to the exposed port
2. 7555
3. I don't think so. Using a fresh chromium install, just to make sure, had the same result.
4. No, the html_scheme is set to http. There are other services using SSL on my server though.

**Comment by novabyte** [comment]
What result do you get when you navigate to this URL from the browser? (Replace with your DNS or IP address)

http://A.A.A.A:7555/ws

You should see error output which looks like:

> Missing or invalid token

**Comment by Lerrrtaste** [comment]
I'm getting exactly that error.

**Comment by novabyte** [comment]
Ok great. That means the server is reachable from the browser and GET requests work to the websocket endpoint.

I think you'll need to share your exact error at this point because I'm not sure what else could be the problem except that maybe the OPTIONS requests are blocked for some reason in your setup. (Required for CORS browser preflights).

**Comment by Lerrrtaste** [comment]
After setting 
``` gdscript
const NK_ADDR = "nk.domain.com"
const NK_PORT = 7555
const NK_KEY = "defaultkey"
const NK_SCHEME = "http"
```

I then create a client like this:
``` gdscript
client = nk.create_client(g.NK_KEY,g.NK_ADDR,g.NK_PORT,g.NK_SCHEME)
```

and try to authenticate:

``` gdscript
session = yield(client.authenticate_custom_async(auth_id,null,true),"completed")
	if session.is_exception():
		$AcceptDialog.dialog_text = session.to_string()
		$AcceptDialog.popup_centered()
		print("Session exception:\n" + session.to_string())
```

session.to_string() returns the following message:
![image](https://user-images.githubusercontent.com/22920627/78138595-75f8af00-7427-11ea-90d8-3c5a99ec5851.png)

Like I said, this works just fine with Linux/X11 and Windows exports, just not on html.

If there's anything else I could provide you, let me know.

**Comment by novabyte** [comment]
Hmmm 🤔 you can reach the server and your authentication code looks fine as far as I can tell. I wonder if its a bug in the HTML5 export with Godot. What version of the engine do you use? Perhaps @Faless can help us.

**Comment by Lerrrtaste** [comment]
I'm using v3.2.1.stable(.custom_build.b0eca5828) but also tried exporting with v3.1.2.stable(.custom_build.0587df4) just now with the same result.

**Comment by Faless** [comment]
I think we still have to update the released version, HTML5 support was fixed in: 6ab107615bd76a3001b343f56f07d576db53c2a2 .
See also the [Changelog](https://github.com/heroiclabs/nakama-godot/blob/master/CHANGELOG.md#fixed).
@Lerrrtaste are you using the `1.0.0` version under release? Can you try using the [latest master branch of this repository](https://github.com/heroiclabs/nakama-godot/archive/master.zip)

**Comment by Lerrrtaste** [comment]
@Faless Yes yes yes, that was it. Thanks a lot :)

**Comment by Faless** [comment]
Cool, we'll try to make a new official release soon :+1:

**Comment by rokasv** [comment]
Hey, I'm encountering a similar problem, which I can't figure out a way around:
- I'm trying to authenticate with the nakama server
- Godot 3.3.2
- authentication is successful on windows, linux, mac and android 
- it fails on html5 
- message returned in-game says `HTTPRequest failed!`
- debugging with chrome inspector shows the failing request status as `(blocked:mixed-content)`
- this happens with both `authenticate_device_async` and `authenticate_email_async`
- following the call (`http://IP:7350/v2/account/authenticate/email?create=true&username=mycustomusername&` using chrome returns `{"code":12, "message":"Method Not Allowed"}`

Is there a step I've missed somewher?

**Comment by Faless** [comment]
@rokasv as you found out in the inspector, chrome (like other browser) blocks mixed content.
You can read more here: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
Basically, if you serve the page as HTTPS, your nakama server must also be reached via HTTPS, not regular HTTP.

**Comment by rokasv** [comment]
seems like I'm in well over my head here, will look into it, thanks

**Comment by ChildLearningClub** [comment]
I also can't seem to to connect to the HTML5 Export. I'm sure it has to do with my configuration, but I don't know what steps to take next to troubleshoot it. I'm using the Nakama docker-compose.yml file setup with nginx docker reverse proxy and terminating ssl letsencrypt certs. when I authenticate with https from two godot clients everything works as expected, but when exporting to html5 I get `connection has failed Device ID is required.` printing the in the console. would this be related to the gdscript or something else? thanks in advance for any help.
