### ISSUE TITLE
socket.add_matchmaker_async does not appear to set the min_count value

### ISSUE THREAD

**Issue by callumlawson** [heroiclabs/nakama-godot#33]
**var query = "*"
	var min_count = 1
	var max_count = 3
	var string_properties = { "region": "europe" }
	var numeric_properties = { "rank": 8 }
	var matchmaker_ticket : NakamaRTAPI.MatchmakerTicket = yield(socket.add_matchmaker_async(query, min_count, max_count, string_properties, numeric_properties),"completed")**

**Actual result:**
An error occured: NakamaException(StatusCode={3}, Message='{Invalid maximum count, must be >= minimum count}', GrpcStatusCode={-1})

**Expected result:**
No error.

While 
**var query = "*"
	var min_count = 3
	var max_count = 1 
	var string_properties = { "region": "europe" }
	var numeric_properties = { "rank": 8 }
	var matchmaker_ticket : NakamaRTAPI.MatchmakerTicket = yield(socket.add_matchmaker_async(query, min_count, max_count, string_properties, numeric_properties),"completed")**

**Actual result:**
No error.

**Expected result:**
An error occured: NakamaException(StatusCode={3}, Message='{Invalid maximum count, must be >= minimum count}', GrpcStatusCode={-1})

Context:
Godot client (script)
Windows 10

**Comment by callumlawson** [comment]
Looking through the code it looks like the min and max counts are reversed in add_matchmaker_async and p_min_count is then never assigned in MatchmakerAdd.

After making those changes a min value of 1 gives:
An error occured: NakamaException(StatusCode={3}, Message='{Invalid minimum count, must be >= 2}', GrpcStatusCode={-1})
and the issue described above appears to be fixed.

**Comment by Faless** [comment]
Nice catch, should be fixed once #34 is merged.
