### ISSUE TITLE
Internal script error! - opcode #0

### ISSUE THREAD

**Issue by pho** [heroiclabs/nakama-godot#35]
I just got this error with the current master (b13e6e6) which asks to be reported
![](https://i.imgur.com/7F5GR95.png)

I'll update this issue as soon as I can get more info or some way to reproduce it

**Comment by Faless** [comment]
That seems like an engine error, if you can make a reproduction project we should report it upstream to Godot Engine issue page.

**Comment by novabyte** [comment]
@pho I'll close this because I think its an engine error. Please reopen if you can demonstrate its an issue in the client sdk.
