### ISSUE TITLE
Signal received_error(p_error) of NakamaSocket never emitted

### ISSUE THREAD

**Issue by github-koop** [heroiclabs/nakama-godot#38]
I maybe found an error in the code.
The received_error signal of the _adapter object of the NakamaSocket is connect to the _closed method, should it be connect to the _error method instead ?

The error was too big so I thought it was maybe a temporary solution because maybe the _error method was not finalize yet. But the _error method seems to be the only one emitting the received_error signal and since the README.md or other documentation use the received_error signal without mentioning any lake of implementation I decided to post this issue.

Can you please tell me if I am wrong what I missed ? I was trying to figure out how server errors were handled and how the _resume_conn function is uses in the NakamaSocket, I would be pleased if you have an once of explication.

**Comment by Faless** [comment]
Thanks for reporting, this looks like a bug. I've opened a PR to fix it (linked above).

**Comment by github-koop** [comment]
Thanks for your work. I found on the Nakama server after the release of the GDQuest YouTube video. Your code and the Nakama server are really simple to use, a couple of days on my spare time to try what I wanted. But I have to admit in therm of error handling, it has become really unclear. For another example, I couldn't find constant or enum values for code errors, but they appear in the Java implementation: [link](https://heroiclabs.github.io/nakama-java/current/com/heroiclabs/nakama/Error.ErrorCode.html)

**Comment by Faless** [comment]
The maybe the proposed fix is wrong, I couldn't find reliable information about errors received by the server, or how exactly `received_error` should be used.
Is it supposed to be emitted when a request ends up returning an exception/grpc error (e.g. bad request)?
Maybe @novabyte can shed some light.

**Comment by github-koop** [comment]
Weird, `onerror` or `received_error` is only mentioned for half for client implementations, on the official Nakama documentation website.

And I come up to this by trying to catch the error mentions in the change log of Nakama server at [2.3.0] - 2018-12-31

> Clients that send data to an invalid match ID will now receive an uncollated error.

Maybe is linked to the received_error signal. Don't know what is an uncollated error.

I post my problem on the heroiclabs forum ([link](https://forum.heroiclabs.com/t/how-to-know-if-a-match-is-still-runnig/737)). No response yet.
