### ISSUE TITLE
Unhandled error Invalid match ID

### ISSUE THREAD

**Issue by koopmyers** [heroiclabs/nakama-godot#42]
This issue is linked to issue #38 that has been closed by #39 . I don't think the fix is correct. I will explain myself.

There are two kinds of errors the client can expect to "received" actually. _Socket errors_ and _server errors_. Example of socket errors are timeout, host not found, connection closed by the host, etc. An example of server error is trying to join a match with an invalid ID. In this case errors are sent by the server through the web socket connection and is as follow: `{error:{code:3, message:Invalid match ID}}`.

```
=== Nakama : DEBUG === Sending async request: MatchDataSend<match_id=a, op_code=1, presences=Null, data=eyJoZWxsbyI6IndvcmxkIn0=>
=== Nakama : WARNING === Unhandled response: {error:{code:3, message:Invalid match ID}}
```
As you can see in the current version this error is not handled, still after the fix of #39.

What I think is that message without a call id and having an error entry should trigger `received_error` signal of NakamaSocket.gd, and it's what is defined as a _server error._ Like a message without a call id and having a match_data entry triggers `received_match_state` signal.

For socket error, it can, of course, still trigger the `received_error` signal as fixed in #39. But I think, socket error and server error should be in separate signal, and socket error should be handled in socket_closed since a socket error closes the socket. This can explain the error report in #38, that, in fact, was not one.

**Comment by dsnopek** [comment]
Thanks!

I understand your concern: the server is returning error messages, but the client isn't making them available to you, only logging them.

Looking at the .NET client, it appears to throw an exception in this case:

https://github.com/heroiclabs/nakama-dotnet/blob/master/Nakama/Socket.cs#L783

And the C++ client also passes these errors to the client listener:

https://github.com/heroiclabs/nakama-cpp/blob/master/src/realtime/NRtClient.cpp#L166

So, it seems like the Godot client should do something with those error messages too! Your suggestion of two different signals for the two types of errors makes sense, but it doesn't look like the other clients do that - they seem to use the same error reporting mechanism for both kinds of errors. So, my feeling at the moment is that Godot should probably use the same signal as well, which would also probably be easier to explain to developers.

**Comment by dsnopek** [comment]
> So, my feeling at the moment is that Godot should probably use the same signal as well, which would also probably be easier to explain to developers.

Hm, looking into this a little more, it looks like in the signal "received_error(error)", the "error" is a value from the [Error enum](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error), so we really shouldn't give it a string. :-( So, this'll either need to change the API of the signal, or make a new signal afterall...
