### ISSUE TITLE
class MatchData missing member var "presence" (bug fix)

### ISSUE THREAD

**Issue by chrutta** [heroiclabs/nakama-godot#44]
Hi,

It seems like class MatchData in "NakamaRTAPI.gd" is missing its "presence" member variable. It is listed in the class _SCHEMA, so after simply adding such a var to the class I was able to decode the sender of the message:

var presence : UserPresence # Add this line to the class body

Sincerely,
chrutta

**Comment by novabyte** [comment]
@chrutta Would you be interested to contribute this change to the client sdk? It would be great to have a pull request for it.

**Comment by Faless** [comment]
I think this is already fixed by #37, but the change is still [unreleased](https://github.com/heroiclabs/nakama-godot/blob/master/CHANGELOG.md).

**Comment by novabyte** [comment]
The latest release is out built from commit ffea07749ac15510d549dc28b7bf3c8432a7bdcb.
