### ISSUE TITLE
Godot 3.2.2 errors on shadowed variables and this breaks NakamaSerializer

### ISSUE THREAD

**Issue by jonbonazza** [heroiclabs/nakama-godot#47]
I personally believe it's a bug and have submitted [an issue to the godot repo](https://github.com/godotengine/godot/issues/39861) as well, however in the mean time, NakamaSerializer (at least, I haven't checked other parts of the code) now breaks thanks to the 3.2.2 GDScript parser erroring on shadowed variables.

the `k` variable [here](https://github.com/heroiclabs/nakama-godot/blob/3e4014a9321bb59bf8d76a9a4d65a3e0ee99738d/addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd#L41) shadows the `k` variable on line 9 and the parser does not like this.

**Comment by novabyte** [comment]
This is resolved in #45. 👍
