### ISSUE TITLE
Android export crashes when using a function from the client in Godot 3.1.2

### ISSUE THREAD

**Issue by JesusAlfMejia** [heroiclabs/nakama-godot#49]
I've been trying the nakama client on my desktop with Godot 3.1.2 and had success with authenticating and matchmaking but when I try to use the addon on android it crashes as soon as a I make a call to the create client function. Any help will be much apreciated :)

**Comment by novabyte** [comment]
@JesusAlfMejia Are there device logs or output of any kind that can be used to identify the problem?

**Comment by JesusAlfMejia** [comment]
Let me see what I can find, the weird thing is that when I export the same project with Godot 3.2 it works fine

**Comment by novabyte** [comment]
@JesusAlfMejia I'll close this issue but reopen if you have more info that there's a client sdk issue on Godot 3.1.2 and its not an engine error.
