### ISSUE TITLE
Godot 3.2.2

### ISSUE THREAD

**Issue by rakkarage** [heroiclabs/nakama-godot#50]
res://addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd:41 - Parse Error: Variable "k" already defined in the scope (at line 9).

since upgrade to new godot nakama not work?
tried making new project with nothing but create and print client and same error
sorry, thanks

**Comment by jknightdoeswork** [comment]
This is fixed on the latest version. Update your nakama.

**Comment by rakkarage** [comment]
thanks. sorry. :)

**Comment by kidandcat** [comment]
This fix is not yet released, right? should we get nakama from master source?

**Comment by novabyte** [comment]
@kidandcat We'll create a new release next week. 👍
