### ISSUE TITLE
Shadowed Variables crash GDScript Parser

### ISSUE THREAD

**Issue by DrFrolicks** [heroiclabs/nakama-godot#51]
Just bringing this: https://github.com/godotengine/godot/issues/39861 to the attention of HeroicLabs.  
The nakama-godot client in its current state is broken because of this. 

I fixed it by changing the names on my end but didn't do a pull request since I'm not sure I'm familiar with naming conventions & best practices.

**Comment by jonbonazza** [comment]
This has already been fixed in master, but i dont think it's been released yet
