### ISSUE TITLE
Prepare for new GDScript syntax (GDScript 2.0)

### ISSUE THREAD

**Issue by vntxx** [heroiclabs/nakama-godot#52]
Probably not an issue now but and it might take a while but once 4.0 releases this addon MAYBE can't be used anymore in its current state as gdscript got an overhaul (more on that [here](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged)). I didn't look into the code yet and it MAY be that this actually works just fine. But if it does break: (did by now and yes it breaks)
 As currently only the development branch (master) is affected I think it would be a good idea to not update master directly but keep a seperate branch for this until 4.0 is ready for release. This way the new implementation can be released simultaneously to 4.0 (and of course the 3.x one can be kept seperate). Might also be a good idea to keep 3.x in a seperate branch (but this depends on whether there will be support for 3.x once 4.0 is out)

**Comment by Faless** [comment]
The main breakage for this repo will likely be the removal of `yield` in favour of `await`. I hoped it would be kept for compatibility in `4.x` but apparently that's not going to be the case.
As you said, it will probably have to go in a new branch (quite a few code changes, although probably not too much work).
Luckily, `4.0` is still months away, since things like subclasses are for now partly broken (last time I tried), and thus we can't really work on porting the SDK for now.

**Comment by elgansayer** [comment]
any updated on this? 4 is closer...

**Comment by grusad** [comment]
bump /\

**Comment by dsnopek** [comment]
There has been some work by @elgansayer on this on https://github.com/heroiclabs/nakama-godot/pull/95

This is going to be a priority fairly soon!

**Comment by dsnopek** [comment]
I've been working on extending @elgansayer's work on PR #103, and it's starting to get interesting! With the current version of the PR on Godot 4.0-alpha7, I'm able to authenticate (device authentication) and write/read some storage objects.

**Comment by dsnopek** [comment]
We now have the ['godot-4' branch](https://github.com/heroiclabs/nakama-godot/tree/godot-4) which works with the current Godot 'master' branch (specifically, I last tested with commit https://github.com/godotengine/godot/commit/532e253a7c0544bfb4866fb00129cfa1d39fcd62).

I'm going to close this issue - I think we are "prepared"! Now it's just a matter of keeping that branch up-to-date with changes to Godot 4.0, which we can work on on other issues and PRs.
