### ISSUE TITLE
Type dictionary serialize doesn't work

### ISSUE THREAD

**Issue by github-koop** [heroiclabs/nakama-godot#53]
Type dictionary are not processed correctly in the NakamaSerializer serialize function.

I tried to use the function 
```
server_client.socket.add_matchmaker_async(maker_query, maker_min_count, maker_max_count, maker_string_properties, maker_numeric_properties)
```
but the server didn't received any properties.

In the master code of serialize:
```
TYPE_DICTIONARY: # Maps
	var dict = {}
	if content == TYPE_OBJECT: # Map of objects
	for l in val:
		if val_type != TYPE_OBJECT:
			continue
		dict[l] = serialize(val)
		        else: # Map of simple types
		for l in val:
			if val_type != content:
				continue
			dict[l] = val
```

We can see two problems, the serialize value `dict` is not put into the out dictionary, and val_type or val is used many times in the place of typeof(val[l]) and val[l]. 

My solution:
```
TYPE_DICTIONARY: # Maps
	var dict = {}
	if content == TYPE_OBJECT: # Map of objects
		for l in val:
			if typeof(val[l]) != TYPE_OBJECT:
				continue
			dict[l] = serialize(val[l])
	else: # Map of simple types
		for l in val:
			if typeof(val[l]) != content:
				continue
			dict[l] = val[l]
				
	out[k] = dict
```

I tested it and it works now

**Comment by fbcosentino** [comment]
I faced the same issue, applied the fix above, but the numeric_properties part is still not working.
When adding a matchmaker entry, line 226 of NakamaSocket.gd calls p_message.serialize(), converting

 MatchmakerAdd<query=properties.rank:>=1, max_count=4, min_count=2, numeric_properties={rank:1}, string_properties={char_id:chem}>

into:

 {"cid":"2","matchmaker_add":{"query":"properties.rank:>=1","max_count":4,"min_count":2,"numeric_properties":{},"string_properties":{"char_id":"chem"}}}
