### ISSUE TITLE
RPC function not found

### ISSUE THREAD

**Issue by darvin7531** [heroiclabs/nakama-godot#55]
I decided to put the nakama on the VDS, but this error appeared when I tried to shove something into the storage

GODOT:
` === Nakama : DEBUG === Request 4 returned response code: 404, RPC code: 5, error: RPC function not found`

there were more warnings when starting docker-compose.yml

Ubuntu:
`nakama         | {"level":"warn","ts":"2020-08-20T07:25:40.186Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.username"}`

`nakama         | {"level":"warn","ts":"2020-08-20T07:25:40.186Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.password"}`

`nakama         | {"level":"warn","ts":"2020-08-20T07:25:40.187Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.signing_key"}`

`nakama         | {"level":"warn","ts":"2020-08-20T07:25:40.187Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"session.encryption_key"}`

`nakama         | {"level":"warn","ts":"2020-08-20T07:25:40.187Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"runtime.http_key"}`

**Comment by darvin7531** [comment]
there are still mistakes in the godot, I can throw it here

**Comment by mofirouz** [comment]
This isn't a Godot client library issue. It looks like you've misconfigured the server and the Lua/Go runtime RPC calls aren't being loaded by the server. 

Please open a forum post and we'll try and help: https://forum.heroiclabs.com
