### ISSUE TITLE
Metadata not sending to server on NakamaSocket#join_match_async

### ISSUE THREAD

**Issue by newnoiseworks** [heroiclabs/nakama-godot#59]
Given an existing match ID, using `NakamaSocket#join_match_async` wasn't passing along the suppled metadata.

I got it working on my local machine with a quick edit; can supply a PR if needed.

https://github.com/heroiclabs/nakama-godot/blob/da6183048f3244fc3ebeb24c7651e1e0580cf1c3/addons/com.heroiclabs.nakama/socket/NakamaSocket.gd#L317 just needs to attach the suppled metadata to the message: `msg.metadata = p_metadata`

**Comment by novabyte** [comment]
@newnoiseworks Thanks for the bug report. I fixed it quickly on master. Pull requests are always welcome though 🙏

**Comment by utkarshtrivedimdz** [comment]
There is a bug. When I try to send metadata even with an empty string I get an error. It works fine if I don't pass any metadata
