### ISSUE TITLE
docker-compose up ERROR: Couldn't connect to Docker daemon

### ISSUE THREAD

**Issue by Shadowblitz16** [heroiclabs/nakama-godot#62]
After following gdquest's tutorial [here](https://www.youtube.com/watch?v=r3T_ED281vU&feature=emb_logo) I ran into this issue when running `docker-compose up`..

```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

I checked my system manager and no godot instances are running
there is no part in the video where he starts the docker

**Comment by jonbonazza** [comment]
This is not a nakama-godot issue.

This is an issue with your docker configuration. What OS are you on?

**Comment by Shadowblitz16** [comment]
Zorin OS 15.3

**Comment by jonbonazza** [comment]
Is the docker daemon started?

Run `docker start` (may need to sudo

You can test if it's started by running `docker ps` but your previous error messages suggests it's not.

**Comment by Shadowblitz16** [comment]
https://youtu.be/r3T_ED281vU?t=394
in the video he says `docker-compose up` starts it so obliviously there is misinfomation

**Comment by jonbonazza** [comment]
Sorry that was my fault. It should be started using whatever servicine manager your os uses, such as

`sudo service docker start`
Or
`sudo systemctl start docker`

Etc...

Afaik docker-compose will not start the docker daemon itself.

**Comment by Shadowblitz16** [comment]
I don't know what service manager is.
I was using zorin os 15.3

**Comment by jonbonazza** [comment]
I dont know anything about zorin. You can try both of fhe commands above and see if one of them works. If docket is running you should be able to run `sudo docker ps` and it should show nothing running

**Comment by Shadowblitz16** [comment]
ok well I will try this some time in the future when I get back into godot.
right now I am trying out the beef language.
for now I will close this.
