### ISSUE TITLE
Document the code generator

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama-godot#70]
NakamaAPI.gd is generated by code/main.go, but there is no instructions on how to run it. This hinders willing contributors ability to update the project and causes the community to be dependant on those in the know.

**Comment by dsnopek** [comment]
The [codegen/README.md](https://github.com/heroiclabs/nakama-godot/tree/master/codegen) file explains how to run it. If you are experiencing a specific problem while following those instructions, please open a new issue with the details. Thanks!
