### ISSUE TITLE
Maybe update the asset Lib?

### ISSUE THREAD

**Issue by TrayserCassa** [heroiclabs/nakama-godot#78]
I am a new Godot developer and kind of new to game development. But working for years now as a DevOps engineer or whatever it's called. I want to say, that Nakama is really great documented and I now this is mostly not the case for this Company size. So great job so far.  👍

I am currently working on my chat implementation and found that this is currently not working in 2.1.0. Somebody fixed this already in 522f01fd4dea8b72ed66bfbe994cb623159c4595. But 2.1.0 is the last version that was published to the asset store and this is close to one year now. So I wondering, would you make a new version in the future, or should I switch to master branch?

**Comment by novabyte** [comment]
@TrayserCassa That's a good reminder. We got a few more updates to make to the SDK and will publish another release. 👍 

In the meantime please open an issues for feedback or errors you've encountered with the SDK on master branch.

**Comment by TrayserCassa** [comment]
I am using now the master branch, because I needed the Party implementation and I am still in development, so I can test the godot client and if I found something I will let you know. 
The chat is working so far, btw :)

The Party stuff is new and lags code examples in the documentation, but for me it is not the Problem, I can read the client code :)

**Comment by novabyte** [comment]
@TrayserCassa No problem I'll keep this issue open until we've pushed a new update to the Asset Library.

**Comment by dsnopek** [comment]
The update to v3.0.0 was finally accepted in the Asset Library!
