### ISSUE TITLE
Serializer discards Matchmaking Properties, breaking the query functionality

### ISSUE THREAD

**Issue by Lerrrtaste** [heroiclabs/nakama-godot#85]
Hello,
it seems like the NakamaSerializer doesn't include the properties for matchmaking, leading to Matchmaking Tickets without any of the given properties. I think my code is correct, but just in case this is what I use to request a matchmaker ticket: 

```gdscript
...
func matchmaking_start_map_async(map_id:int):
	var query = "+properties.map_id:%s"%map_id
	var min_count = 2
	var max_count = 2
	var string_properties = {}
	var numeric_properties = {
		"map_id": map_id
	} 
	matchmaker_ticket = yield(
	  socket.add_matchmaker_async(query, min_count, max_count, string_properties, numeric_properties),
	  "completed"
	)
	if matchmaker_ticket.is_exception():
	  printerr("An error occured: %s" % matchmaker_ticket)
	  return
	print("Got ticket for matchmaking: %s" % [matchmaker_ticket])
	emit_signal("matchmaking_started")`
```

The godot console prints it correctly:

> === Nakama : DEBUG === Sending async request: MatchmakerAdd<query=+properties.map_id:1639436125, max_count=2, min_count=2, numeric_properties={map_id:1639436125}, string_properties={}>

But in the actual request there are neither numeric nor string properties:

> server-nakama-1       | {"level":"debug","ts":"2021-12-14T19:24:23.434Z","caller":"server/pipeline.go:66","msg":"Received *rtapi.Envelope_MatchmakerAdd message","uid":"a5e9f13a-3a2c-4dbf-a490-bc02412fb4f9","sid":"6f6841f3-5d13-11ec-a2e2-7106fdcb5b46","cid":"1","message":{"MatchmakerAdd":{"min_count":2,"max_count":2,"query":"+properties.map_id:1639436125"}}}

Following the debugger, the properties get discarded because of the check in [Line 47 in res://addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd ](https://github.com/heroiclabs/nakama-godot/blob/6a8d703c066a94c6042f6e9519c39c6927da8f56/addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd#L47)

**Comment by Lerrrtaste** [comment]
I have to admit, I didn't see [da61830](https://github.com/heroiclabs/nakama-godot/commit/da6183048f3244fc3ebeb24c7651e1e0580cf1c3) which seems to fix string_properies, but even with the latest master branch code, numeric_properties still don't arrive at the server because of `typeof(val[l]) != content` (in Line 47 of the serializer script) failing with my code from above.

**Comment by novabyte** [comment]
Nice catch @Lerrrtaste. Could you open a pull request? 🙏

**Comment by mikeful** [comment]
What was last version this worked in?

I took bit of a break from my project and my matchmaking no longer works. It might be related to this.
