### ISSUE TITLE
Document which client library version work with/require which Nakama versions

### ISSUE THREAD

**Issue by mikeful** [heroiclabs/nakama-godot#86]
Currently I have no idea if this client library will work after Nakama server update for example. Maybe consider making more releases and mark which server versions it was tested against.

**Comment by mofirouz** [comment]
The server APIs have not changed and only new additions have been added, and therefore the client is both backwards and forward compatible with all the Nakama 2.x and Nakama 3.x releases. I do agree that we have to do more regular releases.
